import { defineTemplate } from "../schema";

const textStyle = { textStyle: true };
const visual = {
  textStyle: true,
  backgroundColor: true,
  backgroundImage: true,
};

export const weddingVerdantVows = defineTemplate({
  id: "wedding-verdant-vows",
  code: "vowgr",
  version: 1,
  category: "wedding",
  name: "Verdant Vows",
  description:
    "Template pernikahan modern dengan botanical line art, opening envelope, navigasi floating, dan empat preset warna dari sage hingga moonlit mauve.",
  price: 50000,
  defaultMusicUrl: "/assets/audio/Banda-Neira-Sampai-Jadi-Debu.mp3",
  navigation: {
    scrollRootSelector: "[data-template-scroll-root]",
    sectionAttribute: "data-template-section",
    openingSectionId: "opening-envelope",
  },
  defaultView: "mobile",
  useContainer: true,
  themes: [
    {
      id: "verdant-sage",
      label: "Verdant Sage",
      colors: {
        background: "#edf4ef",
        surface: "#ffffff",
        primary: "#235f4d",
        accent: "#c3a66a",
        text: "#163b31",
        dark: "#12382f",
        rich: "#1a4c3e",
        mid: "#5f8977",
        cream: "#f7faf6",
        border: "#cfe0d4",
        muted: "#70867e",
      },
      fonts: {
        display: "Great Vibes",
        heading: "Cormorant Garamond",
        body: "Manrope",
      },
    },
    {
      id: "mist-eucalyptus",
      label: "Mist Eucalyptus",
      colors: {
        background: "#f1f7f4",
        surface: "#ffffff",
        primary: "#416f62",
        accent: "#d2b784",
        text: "#1e3f36",
        dark: "#254f44",
        rich: "#315e52",
        mid: "#71998d",
        cream: "#f8fbf9",
        border: "#d7e5dc",
        muted: "#789086",
      },
      fonts: {
        display: "Dancing Script",
        heading: "Cormorant Garamond",
        body: "Manrope",
      },
    },
    {
      id: "forest-ivory",
      label: "Forest & Ivory",
      colors: {
        background: "#f4f5ec",
        surface: "#fffefa",
        primary: "#315a44",
        accent: "#b9985d",
        text: "#233d2f",
        dark: "#1c3427",
        rich: "#274a36",
        mid: "#637e6a",
        cream: "#fbfbf3",
        border: "#d8dfcf",
        muted: "#788274",
      },
      fonts: {
        display: "Great Vibes",
        heading: "Cormorant Garamond",
        body: "Manrope",
      },
    },
    {
      id: "moonlit-mauve",
      label: "Moonlit Mauve",
      colors: {
        background: "#f5f0f6",
        surface: "#fffafe",
        primary: "#6b416d",
        accent: "#d2a45f",
        text: "#36263c",
        dark: "#321f3b",
        rich: "#4c3155",
        mid: "#916f98",
        cream: "#fbf7fc",
        border: "#e3d9e5",
        muted: "#827184",
      },
      fonts: {
        display: "Dancing Script",
        heading: "Cormorant Garamond",
        body: "Manrope",
      },
    },
  ],
  sections: [
    {
      type: "opening-envelope",
      label: "Opening Envelope",
      description: "Amplop pembuka dengan nama tamu.",
      required: true,
      reorderable: false,
      maxInstances: 1,
      capabilities: textStyle,
      fields: [
        { key: "eyebrow", label: "Label pembuka", control: "text" },
        { key: "title", label: "Nama mempelai", control: "text" },
        { key: "date", label: "Tanggal", control: "text" },
        { key: "guestLabel", label: "Label tamu", control: "text" },
        { key: "sealLabel", label: "Teks segel", control: "text" },
        { key: "footer", label: "Catatan bawah", control: "text" },
      ],
      defaultData: {
        title: "Raisa & Arga",
        eyebrow: "The Wedding Of",
        date: "Sabtu, 14 November 2026",
        guestLabel: "Kepada Yth.",
        sealLabel: "Buka Undangan",
        footer: "Dengan penuh sukacita, kami mengundang Anda.",
      },
    },
    {
      type: "hero",
      label: "Hero",
      description: "Cover utama dengan foto mempelai.",
      required: true,
      reorderable: false,
      maxInstances: 1,
      capabilities: { ...visual, image: true },
      fields: [
        { key: "eyebrow", label: "Label section", control: "text" },
        { key: "title", label: "Nama mempelai", control: "text" },
        { key: "subtitle", label: "Tanggal", control: "text" },
        { key: "guestLabel", label: "Label tamu", control: "text" },
        { key: "scrollLabel", label: "Petunjuk scroll", control: "text" },
      ],
      defaultData: {
        title: "Raisa & Arga",
        eyebrow: "Celebrate love, softly",
        subtitle: "14 November 2026 · Bandung",
        guestLabel: "Untuk Bapak/Ibu/Sahabat",
        scrollLabel: "Jelajahi undangan",
        imageLabel: "Foto cover mempelai",
      },
    },
    {
      type: "couple",
      label: "Mempelai",
      description: "Cerita singkat kedua mempelai.",
      required: true,
      reorderable: true,
      maxInstances: 1,
      capabilities: { ...visual, image: true },
      fields: [
        { key: "eyebrow", label: "Label section", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "intro", label: "Pengantar", control: "textarea", rows: 3 },
        { key: "brideName", label: "Nama mempelai wanita", control: "text" },
        {
          key: "brideParents",
          label: "Orang tua mempelai wanita",
          control: "textarea",
          rows: 2,
        },
        { key: "groomName", label: "Nama mempelai pria", control: "text" },
        {
          key: "groomParents",
          label: "Orang tua mempelai pria",
          control: "textarea",
          rows: 2,
        },
      ],
      defaultData: {
        title: "Perkenalkan mempelai",
        eyebrow: "Mempelai",
        intro:
          "Kami memperkenalkan dua pribadi yang akan memulai perjalanan baru bersama.",
        brideName: "Raisa Maharani",
        brideParents: "Putri dari Bapak Hendra & Ibu Maya",
        groomName: "Arga Pratama",
        groomParents: "Putra dari Bapak Dimas & Ibu Laras",
        imageUrls: [],
        imageMax: 2,
        imageLabel: "Foto The Bride & The Groom",
      },
    },
    {
      type: "event",
      label: "Rangkaian Acara",
      description: "Waktu, lokasi, dan tautan peta.",
      required: true,
      reorderable: true,
      maxInstances: 1,
      capabilities: { ...visual, map: true },
      fields: [
        { key: "eyebrow", label: "Kicker", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "day", label: "Hari", control: "text" },
        { key: "date", label: "Tanggal", control: "text" },
        { key: "dressCodeLabel", label: "Label dress code", control: "text" },
        { key: "dressCode", label: "Dress code", control: "text" },
        {
          key: "dressCodeNote",
          label: "Catatan dress code",
          control: "textarea",
          rows: 2,
        },
        { key: "akadTime", label: "Waktu akad", control: "text" },
        { key: "receptionTime", label: "Waktu resepsi", control: "text" },
        { key: "venue", label: "Nama venue", control: "text" },
        { key: "address", label: "Alamat", control: "textarea", rows: 3 },
        { key: "mapUrl", label: "URL Google Maps", control: "url" },
        { key: "buttonLabel", label: "Teks tombol Maps", control: "text" },
        {
          key: "calendarLabel",
          label: "Teks tombol kalender",
          control: "text",
        },
      ],
      defaultData: {
        title: "Hari yang kami nantikan",
        eyebrow: "Save the date",
        day: "Sabtu",
        date: "14 November 2026",
        dressCodeLabel: "Dress code",
        dressCode: "Sage, ivory & champagne",
        dressCodeNote:
          "Kenakan nuansa lembut untuk merayakan hari kami bersama.",
        akadTime: "08.00 WIB",
        receptionTime: "11.00 – 14.00 WIB",
        venue: "Taman Hutan Raya",
        address: "Jl. Ir. H. Juanda No. 99, Dago, Bandung",
        mapUrl:
          "https://www.google.com/maps/search/?api=1&query=Taman+Hutan+Raya+Juanda+Bandung",
        buttonLabel: "Buka Google Maps",
        calendarLabel: "Simpan ke kalender",
      },
    },
    {
      type: "story",
      label: "Perjalanan Kami",
      description:
        "Timeline perjalanan dari berkenalan hingga menuju pernikahan.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: visual,
      fields: [
        { key: "eyebrow", label: "Label section", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "intro", label: "Pengantar", control: "textarea", rows: 2 },
        { key: "firstDate", label: "Tahun pertama", control: "text" },
        { key: "firstTitle", label: "Judul momen pertama", control: "text" },
        {
          key: "firstCopy",
          label: "Cerita momen pertama",
          control: "textarea",
          rows: 2,
        },
        { key: "secondDate", label: "Tahun kedua", control: "text" },
        { key: "secondTitle", label: "Judul momen kedua", control: "text" },
        {
          key: "secondCopy",
          label: "Cerita momen kedua",
          control: "textarea",
          rows: 2,
        },
        { key: "thirdDate", label: "Tahun ketiga", control: "text" },
        { key: "thirdTitle", label: "Judul momen ketiga", control: "text" },
        {
          key: "thirdCopy",
          label: "Cerita momen ketiga",
          control: "textarea",
          rows: 2,
        },
      ],
      defaultData: {
        title: "Perjalanan kami",
        eyebrow: "Dari perkenalan hingga selamanya",
        intro:
          "Sebuah perjalanan sederhana yang akhirnya membawa kami pada hari istimewa ini.",
        firstDate: "2020",
        firstTitle: "Berkenalan",
        firstCopy:
          "Dari sebuah percakapan kecil, kami menemukan kenyamanan yang terasa begitu akrab.",
        secondDate: "2023",
        secondTitle: "Menumbuhkan keyakinan",
        secondCopy:
          "Kami belajar saling berjalan, mendengar, dan merayakan banyak hal sederhana bersama.",
        thirdDate: "2026",
        thirdTitle: "Menuju selamanya",
        thirdCopy:
          "Dengan doa keluarga, kami memilih untuk melangkah ke jenjang pernikahan.",
      },
    },
    {
      type: "gallery",
      label: "Galeri",
      description: "Momen-momen pilihan mempelai.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: { ...visual, gallery: true },
      fields: [
        { key: "eyebrow", label: "Kicker", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "subtitle", label: "Caption", control: "text" },
      ],
      defaultData: {
        title: "Momen yang tumbuh bersama",
        eyebrow: "Little chapters",
        subtitle: "Sepotong cerita yang membawa kami sampai ke hari ini.",
        imageLabel: "4 foto galeri",
        imageUrls: [],
      },
    },
    {
      type: "gift",
      label: "Hadiah",
      description: "Tanda kasih digital.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: { ...visual, image: true },
      fields: [
        { key: "eyebrow", label: "Kicker", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "subtitle", label: "Deskripsi", control: "textarea", rows: 3 },
        { key: "bank1", label: "Nama bank", control: "text" },
        { key: "account1", label: "Nomor rekening", control: "text" },
        { key: "holder1", label: "Nama pemilik", control: "text" },
        { key: "bank2", label: "Nama bank / e-wallet kedua", control: "text" },
        { key: "account2", label: "Nomor rekening kedua", control: "text" },
        { key: "holder2", label: "Nama pemilik kedua", control: "text" },
        { key: "buttonLabel", label: "Teks tombol salin", control: "text" },
        { key: "qrisLabel", label: "Label QRIS", control: "text" },
      ],
      defaultData: {
        title: "Tanda kasih",
        eyebrow: "With gratitude",
        subtitle:
          "Kehadiran dan doa Anda adalah hadiah terbaik. Bila berkenan berbagi tanda kasih, dapat melalui rekening berikut.",
        bank1: "BCA",
        account1: "123 456 7890",
        holder1: "a.n. Raisa Maharani",
        bank2: "DANA",
        account2: "0812 3456 7890",
        holder2: "a.n. Arga Pratama",
        buttonLabel: "Salin nomor",
        qrisLabel: "Scan QRIS tanda kasih",
        showBank: true,
        hasSecondAccount: false,
        showQris: true,
        imageUrl: "",
        imageLabel: "Unggah QRIS dari Asset Manager",
      },
    },
    {
      type: "wishes",
      label: "Ucapan",
      description: "Buku tamu dan doa untuk mempelai.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: visual,
      fields: [
        { key: "eyebrow", label: "Kicker", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "subtitle", label: "Deskripsi", control: "text" },
        { key: "namePlaceholder", label: "Placeholder nama", control: "text" },
        {
          key: "messagePlaceholder",
          label: "Placeholder ucapan",
          control: "text",
        },
        { key: "submitLabel", label: "Teks tombol kirim", control: "text" },
        {
          key: "attendanceLabel",
          label: "Label RSVP",
          control: "text",
        },
        {
          key: "attendancePresentLabel",
          label: "Pilihan hadir",
          control: "text",
        },
        {
          key: "attendanceUnsureLabel",
          label: "Pilihan belum pasti",
          control: "text",
        },
        {
          key: "attendanceAbsentLabel",
          label: "Pilihan berhalangan",
          control: "text",
        },
      ],
      defaultData: {
        title: "Titipkan doa baik",
        eyebrow: "For the newlyweds",
        subtitle:
          "Kata-kata Anda akan menjadi kenangan yang selalu kami simpan.",
        namePlaceholder: "Nama Anda",
        messagePlaceholder: "Tulis ucapan dan doa",
        submitLabel: "Kirim ucapan",
        attendanceLabel: "Konfirmasi kehadiran",
        attendancePresentLabel: "Hadir",
        attendanceUnsureLabel: "Belum pasti",
        attendanceAbsentLabel: "Berhalangan hadir",
      },
    },
    {
      type: "closing",
      label: "Penutup",
      description: "Ucapan terima kasih dari mempelai.",
      required: true,
      reorderable: true,
      maxInstances: 1,
      capabilities: visual,
      fields: [
        { key: "title", label: "Judul", control: "text" },
        { key: "copy", label: "Ucapan penutup", control: "textarea", rows: 3 },
        { key: "subtitle", label: "Nama mempelai", control: "text" },
      ],
      defaultData: {
        title: "Terima kasih",
        copy: "Terima kasih telah meluangkan waktu, doa, dan kehangatan untuk merayakan awal kisah kami.",
        subtitle: "Raisa & Arga",
      },
    },
  ],
  defaultSections: [
    "opening-envelope",
    "hero",
    "couple",
    "event",
    "story",
    "gallery",
    "gift",
    "wishes",
    "closing",
  ],
});
