import { defineTemplate } from "../schema";

const theme = (id: string, label: string, colors: { background: string; surface: string; primary: string; accent: string; text: string; dark: string; rich: string; mid: string; cream: string; border: string; muted: string }) => ({ id, label, colors, fonts: { display: "Great Vibes", heading: "Cormorant Garamond", body: "Manrope" } });

export const birthdayCelestial = defineTemplate({
  id: "birthday-celestial",
  code: "bdcel",
  version: 2,
  category: "birthday",
  name: "Celestial Birthday",
  description: "Undangan ulang tahun modern dengan nuansa langit malam dan aksen bintang.",
  price: 35000,
  defaultMusicUrl: "/assets/audio/happy-birthday-ukulele.mp3",
  navigation: { scrollRootSelector: "[data-template-scroll-root]", sectionAttribute: "data-template-section", openingSectionId: "opening-envelope" },
  defaultView: "mobile",
  themes: [
    theme("midnight-lilac", "Midnight Lilac", { background: "#f8f5ff", surface: "#ffffff", primary: "#5b3f88", accent: "#efb94f", text: "#30254b", dark: "#201637", rich: "#38245e", mid: "#8060aa", cream: "#fff8e8", border: "#d6c4ef", muted: "#766d91" }),
    theme("sunset-peach", "Sunset Peach", { background: "#fff7f3", surface: "#fffdfb", primary: "#ad5268", accent: "#e89a4d", text: "#4d2832", dark: "#48212e", rich: "#753547", mid: "#cf7181", cream: "#fff2db", border: "#f2c6ad", muted: "#8d6972" }),
    theme("sky-mint", "Sky Mint", { background: "#f2fbfa", surface: "#ffffff", primary: "#357b78", accent: "#e0a44a", text: "#214846", dark: "#173c3b", rich: "#265e5b", mid: "#5b9b96", cream: "#fff8e9", border: "#bae1db", muted: "#66817e" }),
  ],
  sections: [
    { type: "opening-envelope", label: "Opening Envelope", description: "Amplop pembuka dengan nama tamu.", required: true, reorderable: false, maxInstances: 1, capabilities: { textStyle: true }, fields: [{ key: "title", label: "Nama perayaan", control: "text" }, { key: "subtitle", label: "Tanggal", control: "text" }], defaultData: { title: "Naya Turns 17", subtitle: "18 · 10 · 2026" } },
    {
      type: "hero",
      label: "Hero Ulang Tahun",
      description: "Nama, foto, dan tanggal perayaan.",
      required: true,
      reorderable: false,
      maxInstances: 1,
      capabilities: { image: true, backgroundImage: true, backgroundColor: true, textStyle: true },
      fields: [
        { key: "kicker", label: "Label perayaan (Kicker)", control: "text" },
        { key: "title", label: "Nama perayaan", control: "text" },
        { key: "subtitle", label: "Tanggal acara", control: "text" },
        { key: "guestLabel", label: "Label nama tamu", control: "text" },
        { key: "copy", label: "Pesan pembuka", control: "textarea", rows: 2 },
      ],
      defaultData: {
        kicker: "✦ HAPPY SWEET 17TH ✦",
        title: "Happy Birthday, Naya!",
        subtitle: "Sabtu, 18 Oktober 2026",
        guestLabel: "Kepada Yth.",
        copy: "Mari rayakan hari istimewa ini bersama-sama.",
        imageUrl: "",
        imageLabel: "Pilih foto celebrant dari Asset Manager",
        backgroundImageUrl: "",
        backgroundImageLabel: "Pilih gambar latar dari Asset Manager",
      },
    },
    { type: "event", label: "Detail Acara", description: "Waktu, lokasi, dan tautan Google Maps pesta.", required: true, reorderable: true, maxInstances: 1, capabilities: { backgroundColor: true, map: true, textStyle: true }, fields: [{ key: "title", label: "Judul", control: "text" }, { key: "subtitle", label: "Waktu", control: "text" }, { key: "address", label: "Lokasi", control: "textarea", rows: 2 }, { key: "mapUrl", label: "URL Google Maps", control: "url" }, { key: "mapLabel", label: "Teks tombol peta", control: "text" }], defaultData: { title: "Birthday Party", subtitle: "16.00 WIB sampai selesai", address: "Sky Garden, Bandar Lampung", mapUrl: "https://maps.google.com/?q=Sky+Garden+Bandar+Lampung", mapLabel: "Buka Google Maps" } },
    { type: "gallery", label: "Galeri", description: "Kenangan bahagia.", required: false, reorderable: true, maxInstances: 1, capabilities: { gallery: true, backgroundColor: true, textStyle: true }, fields: [{ key: "title", label: "Judul", control: "text" }, { key: "subtitle", label: "Caption", control: "text" }], defaultData: { title: "Little Moments", subtitle: "Senyum, tawa, dan kenangan.", imageLabel: "Pilih foto galeri (Maks 4)", imageUrls: [] } },
    {
      type: "gift",
      label: "Kirim Hadiah",
      description: "Rekening dan QRIS untuk hadiah digital.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: { image: true, backgroundColor: true, textStyle: true },
      fields: [
        { key: "eyebrow", label: "Label section", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "subtitle", label: "Deskripsi", control: "textarea", rows: 3 },
        { key: "bank", label: "Nama bank / e-wallet", control: "text" },
        { key: "account", label: "Nomor rekening", control: "text" },
        { key: "holder", label: "Nama pemilik", control: "text" },
        { key: "bank2", label: "Nama bank / e-wallet kedua", control: "text" },
        { key: "account2", label: "Nomor rekening kedua", control: "text" },
        { key: "holder2", label: "Nama pemilik kedua", control: "text" },
        { key: "copyLabel", label: "Teks tombol salin", control: "text" },
        { key: "qrisLabel", label: "Label QRIS", control: "text" },
      ],
      defaultData: {
        eyebrow: "A LITTLE GIFT",
        title: "Kirim Hadiah",
        subtitle: "Kehadiran dan doa terbaikmu sudah sangat berarti. Jika berkenan, hadiah digital dapat dikirim melalui berikut ini.",
        bank: "BANK BCA",
        account: "1234 5678 90",
        holder: "a.n. Naya Putri",
        copyLabel: "Salin nomor",
        qrisLabel: "Scan QRIS",
        showBank: true,
        hasSecondAccount: false,
        bank2: "BANK BNI",
        account2: "",
        holder2: "",
        showQris: true,
        imageUrl: "",
        imageLabel: "Unggah gambar QRIS dari Asset Manager",
      },
    },
    { type: "wishes", label: "Ucapan", description: "Doa dari para tamu.", required: false, reorderable: true, maxInstances: 1, capabilities: { textStyle: true }, fields: [{ key: "title", label: "Judul", control: "text" }, { key: "subtitle", label: "Deskripsi", control: "text" }], defaultData: { title: "Kirim Ucapan", subtitle: "Doa terbaikmu adalah hadiah yang paling berarti." } },
    { type: "closing", label: "Penutup", description: "Ucapan terima kasih.", required: true, reorderable: true, maxInstances: 1, capabilities: { backgroundColor: true, textStyle: true }, fields: [{ key: "title", label: "Judul", control: "text" }, { key: "subtitle", label: "Pesan", control: "textarea", rows: 3 }], defaultData: { title: "See You at the Party!", subtitle: "Terima kasih sudah menjadi bagian dari hari bahagia ini." } },
  ],
  defaultSections: ["opening-envelope", "hero", "event", "gallery", "gift", "wishes", "closing"],
});
