import { defineTemplate } from "../schema";

const photos = {
  lampungCover: "/assets/my/DSC_0680%20(2).jpg.jpeg",
  lampungPortrait: "/assets/my/DSC_0701%20(1).jpg.jpeg",
  jawaFirst: "/assets/my/DSC_0838%20(1).jpg.jpeg",
  jawaSecond: "/assets/my/DSC_0872%20(1).jpg.jpeg",
  quote: "/assets/my/DSC_0889%20(1).jpg.jpeg",
  lampungGallery: "/assets/my/DSC_0711%20(1).jpg.jpeg",
} as const;

export const weddingLampungElegance = defineTemplate({
  id: "wedding-lampung-elegance",
  code: "hjydg",
  version: 2,
  category: "wedding",
  name: "Wedding Elegance",
  description: "Template pernikahan 2 culture dengan opening envelope, aksen emas mewah, dan audio player.",
  price: 50000,
  defaultMusicUrl: "/assets/audio/easy-on-me.webm",
  navigation: {
    scrollRootSelector: "[data-template-scroll-root]",
    sectionAttribute: "data-template-section",
    openingSectionId: "opening-envelope",
  },
  defaultView: "mobile",
  useContainer: true,
  themes: [
    {
      id: "blue-gold",
      // Keep the historical id so saved drafts remain compatible.
      label: "Terracotta & Gold",
      colors: { background: "#fff7f0", surface: "#fffaf6", primary: "#994b36", accent: "#d2a24b", text: "#472b25", dark: "#42231e", rich: "#633026", mid: "#b96a50", cream: "#fff4e8", border: "#d2a24b", muted: "#8b6e62" },
      fonts: { display: "Great Vibes", heading: "Cormorant Garamond", body: "Manrope" },
    },
    {
      id: "maroon-gold",
      label: "Maroon & Gold",
      colors: { background: "#fdf7eb", surface: "#fffaf0", primary: "#5b232d", accent: "#caa254", text: "#382326", dark: "#2c0e13", rich: "#50151d", mid: "#722a35", cream: "#fff5dc", border: "#e4c880", muted: "#756b66" },
      fonts: { display: "Great Vibes", heading: "Cormorant Garamond", body: "Manrope" },
    },
    {
      id: "ivory-gold",
      label: "Ivory & Gold",
      colors: { background: "#fffdf7", surface: "#fffaf5", primary: "#78613b", accent: "#bb923f", text: "#443c2d", dark: "#3e321d", rich: "#5d4828", mid: "#9b7c43", cream: "#fff9ec", border: "#bb923f", muted: "#7e7a61" },
      fonts: { display: "Great Vibes", heading: "Cormorant Garamond", body: "Manrope" },
    },
    {
      id: "sage-gold",
      label: "Sage & Gold",
      colors: { background: "#f7f8ef", surface: "#fbfbf5", primary: "#4d665b", accent: "#c29c4d", text: "#33453b", dark: "#20372c", rich: "#314b3b", mid: "#6f8778", cream: "#f5faf2", border: "#c29c4d", muted: "#4d665b" },
      fonts: { display: "Dancing Script", heading: "Cormorant Garamond", body: "Cormorant Garamond" },
    },
  ],
  sections: [
    {
      type: "opening-envelope",
      label: "Opening Envelope",
      description: "Amplop pembuka dengan nama tamu.",
      required: true,
      reorderable: false,
      maxInstances: 1,
      fields: [
        { key: "eyebrow", label: "Label pembuka", control: "text" },
        { key: "kicker", label: "Kicker", control: "text" },
        { key: "title", label: "Nama mempelai", control: "text" },
        { key: "date", label: "Tanggal", control: "text" },
        { key: "guestLabel", label: "Label nama tamu", control: "text" },
        { key: "sealMonogram", label: "Monogram segel", control: "text" },
        { key: "sealLabel", label: "Teks segel", control: "text" },
        { key: "callout", label: "Judul petunjuk", control: "text" },
        { key: "subtitle", label: "Petunjuk segel", control: "text" },
        { key: "footer", label: "Catatan bawah", control: "text" },
      ],
      defaultData: {
        eyebrow: "Dengan penuh kebahagiaan",
        kicker: "The Wedding of",
        title: "Ayu & Ardi",
        date: "26 · 09 · 2026",
        guestLabel: "Kepada Yth.",
        sealMonogram: "A & A",
        sealLabel: "Buka",
        callout: "Klik di sini",
        subtitle: "untuk membuka",
        footer: "Sebuah undangan istimewa untuk Anda",
      },
    },
    {
      type: "hero",
      label: "Hero",
      description: "Cover utama undangan.",
      required: true,
      reorderable: false,
      maxInstances: 1,
      fields: [
        { key: "monogram", label: "Monogram atas", control: "text" },
        { key: "kicker", label: "Kicker", control: "text" },
        { key: "title", label: "Nama mempelai", control: "text" },
        { key: "subtitle", label: "Tanggal", control: "text" },
        { key: "guestLabel", label: "Label nama tamu", control: "text" },
        { key: "scrollLabel", label: "Petunjuk scroll", control: "text" },
      ],
      defaultData: {
        monogram: "A & A",
        kicker: "The Wedding of",
        title: "Ayu & Ardi",
        subtitle: "Sabtu · 26 September · 2026",
        guestLabel: "Kepada Yth.",
        scrollLabel: "Scroll",
        imageLabel: "Foto cover Lampung",
        imageUrl: photos.lampungCover,
      },
    },
    {
      type: "couple",
      label: "Mempelai",
      description: "Profil kedua mempelai.",
      required: true,
      reorderable: true,
      maxInstances: 1,
      fields: [
        { key: "bismillah", label: "Bismillah", control: "text" },
        { key: "greeting", label: "Salam pembuka", control: "text" },
        { key: "subtitle", label: "Kalimat pembuka", control: "textarea", rows: 3 },
        { key: "brideLabel", label: "Label mempelai wanita", control: "text" },
        { key: "brideName", label: "Nama mempelai wanita", control: "text" },
        { key: "brideOrder", label: "Keterangan mempelai wanita", control: "text" },
        { key: "brideParents", label: "Orang tua mempelai wanita", control: "textarea", rows: 2 },
        { key: "groomLabel", label: "Label mempelai pria", control: "text" },
        { key: "groomName", label: "Nama mempelai pria", control: "text" },
        { key: "groomOrder", label: "Keterangan mempelai pria", control: "text" },
        { key: "groomParents", label: "Orang tua mempelai pria", control: "textarea", rows: 2 },
      ],
      defaultData: {
        title: "Dwi Wahyulita, Amd.Kep & Ardi Mahendra, S.Kom",
        bismillah: "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيْم",
        greeting: "Assalamu’alaikum Warahmatullahi Wabarakatuh",
        subtitle: "Dengan memohon rahmat dan rida Allah SWT, kami bermaksud menyelenggarakan pernikahan putra-putri kami.",
        brideLabel: "The Bride",
        brideName: "Dwi Wahyulita, Amd.Kep",
        brideOrder: "Putri kedua dari",
        brideParents: "Bapak Suhaimi & Ibu Nurhayati, S.Pd.I (Almh)",
        groomLabel: "The Groom",
        groomName: "Ardi Mahendra, S.Kom",
        groomOrder: "Putra pertama dari",
        groomParents: "Bapak Agus Hartoyo & Ibu Sri Suwarni",
        imageLabel: "Foto portrait mempelai",
        imageUrl: photos.lampungPortrait,
      },
    },
    {
      type: "countdown",
      label: "Hitung Mundur",
      description: "Hitung mundur menuju hari pernikahan.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      fields: [
        { key: "subtitle", label: "Label", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "targetDate", label: "Target tanggal & waktu", control: "datetime-local" },
        { key: "daysLabel", label: "Label hari", control: "text" },
        { key: "hoursLabel", label: "Label jam", control: "text" },
        { key: "minutesLabel", label: "Label menit", control: "text" },
        { key: "secondsLabel", label: "Label detik", control: "text" },
        { key: "buttonLabel", label: "Teks tombol kalender", control: "text" },
        { key: "calendarUrl", label: "URL kalender", control: "url" },
      ],
      defaultData: {
        title: "Menuju Hari Bahagia",
        subtitle: "Save the Date",
        targetDate: "2026-09-26T08:00",
        daysLabel: "Hari",
        hoursLabel: "Jam",
        minutesLabel: "Menit",
        secondsLabel: "Detik",
        buttonLabel: "Simpan Tanggal",
        calendarUrl: "https://calendar.google.com/calendar/render?action=TEMPLATE&text=The%20Wedding%20of%20Ayu%20%26%20Ardi&dates=20260926T010000Z/20260926T070000Z",
        backgroundImageLabel: "Foto latar hitung mundur",
        backgroundImageUrl: photos.jawaFirst,
      },
    },
    {
      type: "event",
      label: "Rangkaian Acara",
      description: "Akad dan resepsi.",
      required: true,
      reorderable: true,
      maxInstances: 1,
      fields: [
        { key: "eyebrow", label: "Label section", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "subtitle", label: "Kalimat pengantar", control: "text" },
        { key: "day", label: "Hari", control: "text" },
        { key: "date", label: "Tanggal", control: "text" },
        { key: "monthYear", label: "Bulan dan tahun", control: "text" },
        { key: "akadTitle", label: "Nama acara akad", control: "text" },
        { key: "akadTime", label: "Waktu akad", control: "text" },
        { key: "akadNote", label: "Catatan akad", control: "text" },
        { key: "receptionTitle", label: "Nama acara resepsi", control: "text" },
        { key: "receptionTime", label: "Waktu resepsi", control: "text" },
        { key: "receptionNote", label: "Catatan resepsi", control: "text" },
      ],
      defaultData: {
        eyebrow: "Rangkaian Acara",
        title: "Hari Bahagia Kami",
        subtitle: "Insya Allah akan dilaksanakan pada:",
        day: "Sabtu",
        date: "26",
        monthYear: "September 2026",
        akadTitle: "Akad Nikah",
        akadTime: "08.30 WIB s.d selesai",
        akadNote: "Pagi hari",
        receptionTitle: "Resepsi",
        receptionTime: "10.00 – 14.00 WIB",
        receptionNote: "Sampai selesai",
      },
    },
    {
      type: "map",
      label: "Lokasi",
      description: "Peta dan alamat acara.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      fields: [
        { key: "title", label: "Label lokasi", control: "text" },
        { key: "subtitle", label: "Alamat", control: "textarea", rows: 4 },
        { key: "mapUrl", label: "URL Google Maps", control: "url" },
        { key: "buttonLabel", label: "Teks tombol Maps", control: "text" },
      ],
      defaultData: {
        title: "Lokasi Akad & Resepsi",
        subtitle: "Dusun Srimenanti, RT.006, RW.03, Desa Negeri Sakti, Kec. Gedong Tataan, Kab. Pesawaran, Lampung",
        mapUrl: "https://maps.app.goo.gl/VyDtPVWhuAiGULfy8",
        buttonLabel: "Buka Google Maps",
      },
    },
    {
      type: "unduh-mantu",
      label: "Unduh Mantu",
      description: "Acara tambahan pihak pria.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      fields: [
        { key: "kicker", label: "Keterangan", control: "text" },
        { key: "title", label: "Nama acara", control: "text" },
        { key: "subtitle", label: "Tanggal acara", control: "text" },
        { key: "address", label: "Alamat", control: "textarea", rows: 3 },
        { key: "mapUrl", label: "URL Google Maps", control: "url" },
        { key: "buttonLabel", label: "Teks tombol Maps", control: "text" },
      ],
      defaultData: {
        title: "Unduh Mantu",
        subtitle: "Senin, 28 September 2026",
        kicker: "Acara Keluarga Mempelai Pria",
        address: "Desa Sinar Seputih, RT.001/RW.001, Kec. Bangunrejo, Lampung Tengah",
        mapUrl: "https://www.google.com/maps/place/5%C2%B007'45.0%22S+105%C2%B003'03.2%22E/@-5.1291577,105.0483231,17z",
        buttonLabel: "Buka Google Maps",
      },
    },
    {
      type: "quote",
      label: "Quote",
      description: "Ayat atau kutipan pilihan.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      fields: [
        { key: "title", label: "Kutipan", control: "textarea", rows: 5 },
        { key: "subtitle", label: "Sumber", control: "text" },
      ],
      defaultData: {
        title: "Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu pasangan hidup dari jenismu sendiri, supaya kamu merasa tenteram di sampingnya.",
        subtitle: "QS. Ar-Rum: 21",
        imageLabel: "Foto latar quote",
        imageUrl: photos.quote,
      },
    },
    {
      type: "gallery",
      label: "Galeri",
      description: "Kumpulan foto bahagia.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      fields: [
        { key: "eyebrow", label: "Label section", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "viewLabel", label: "Label preview foto", control: "text" },
        { key: "subtitle", label: "Caption", control: "text" },
        { key: "lightboxTitle", label: "Nama di lightbox", control: "text" },
      ],
      defaultData: {
        eyebrow: "Our Moments",
        title: "Galeri Bahagia",
        viewLabel: "lihat foto",
        subtitle: "Two cultures, one beautiful story.",
        lightboxTitle: "Ayu & Ardi",
        imageLabel: "4 foto galeri",
        imageUrls: [photos.lampungCover, photos.jawaFirst, photos.lampungGallery, photos.jawaSecond],
      },
    },
    {
      type: "gift",
      label: "Hadiah",
      description: "Rekening atau hadiah digital.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      fields: [
        { key: "eyebrow", label: "Label section", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "subtitle", label: "Deskripsi", control: "textarea", rows: 4 },
        { key: "bank1", label: "Bank pertama", control: "text" },
        { key: "account1", label: "Nomor rekening pertama", control: "text" },
        { key: "holder1", label: "Pemilik rekening pertama", control: "text" },
        { key: "bank2", label: "Bank kedua", control: "text" },
        { key: "account2", label: "Nomor rekening kedua", control: "text" },
        { key: "holder2", label: "Pemilik rekening kedua", control: "text" },
        { key: "buttonLabel", label: "Teks tombol salin", control: "text" },
        { key: "copiedLabel", label: "Teks setelah disalin", control: "text" },
      ],
      defaultData: {
        eyebrow: "Tanda Kasih",
        title: "Wedding Gift",
        subtitle: "Doa restu Anda merupakan hadiah terindah bagi kami. Namun bila ingin memberikan tanda kasih, dapat melalui rekening berikut.",
        bank1: "Bank BCA",
        account1: "775 176 1019",
        holder1: "a.n. Ardi Mahendra",
        bank2: "Bank BNI",
        account2: "185 300 7509",
        holder2: "a.n. Dwi Wahyulita",
        buttonLabel: "Salin nomor",
        copiedLabel: "Tersalin",
      },
    },
    {
      type: "wishes",
      label: "Ucapan",
      description: "Kehadiran dan buku tamu.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      fields: [
        { key: "eyebrow", label: "Label section", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "formTitle", label: "Judul form", control: "text" },
        { key: "subtitle", label: "Deskripsi form", control: "text" },
        { key: "nameLabel", label: "Label nama", control: "text" },
        { key: "namePlaceholder", label: "Placeholder nama", control: "text" },
        { key: "attendanceLabel", label: "Label kehadiran", control: "text" },
        { key: "presentLabel", label: "Pilihan hadir", control: "text" },
        { key: "unsureLabel", label: "Pilihan belum pasti", control: "text" },
        { key: "absentLabel", label: "Pilihan berhalangan", control: "text" },
        { key: "messageLabel", label: "Label ucapan", control: "text" },
        { key: "messagePlaceholder", label: "Placeholder ucapan", control: "text" },
        { key: "submitLabel", label: "Teks tombol kirim", control: "text" },
        { key: "savingLabel", label: "Teks saat menyimpan", control: "text" },
        { key: "successLabel", label: "Pesan berhasil", control: "text" },
        { key: "celebrationLabel", label: "Pesan animasi", control: "text" },
        { key: "loadingLabel", label: "Pesan saat memuat", control: "text" },
        { key: "emptyLabel", label: "Pesan saat kosong", control: "text" },
      ],
      defaultData: {
        eyebrow: "Kirim Doa",
        title: "Ucapan & Kehadiran",
        formTitle: "Tinggalkan Pesan",
        subtitle: "Setiap doa adalah hadiah terindah bagi kami",
        nameLabel: "Nama Anda",
        namePlaceholder: "Tulis nama lengkap",
        attendanceLabel: "Konfirmasi Kehadiran",
        presentLabel: "Hadir",
        unsureLabel: "Belum pasti",
        absentLabel: "Berhalangan hadir",
        messageLabel: "Ucapan & Doa",
        messagePlaceholder: "Tuliskan doa terbaik untuk kedua mempelai…",
        submitLabel: "Kirim Ucapan",
        savingLabel: "Menyimpan…",
        successLabel: "Ucapan berhasil tersimpan.",
        celebrationLabel: "Terima kasih atas doanya!",
        loadingLabel: "Memuat ucapan…",
        emptyLabel: "Jadilah yang pertama mengirimkan doa terbaik.",
      },
    },
    {
      type: "closing",
      label: "Penutup",
      description: "Ucapan terima kasih.",
      required: true,
      reorderable: true,
      maxInstances: 1,
      fields: [
        { key: "title", label: "Judul", control: "text" },
        { key: "copy", label: "Ucapan penutup", control: "textarea", rows: 4 },
        { key: "subtitle", label: "Nama mempelai", control: "text" },
        { key: "greeting", label: "Salam penutup", control: "text" },
        { key: "date", label: "Tanggal", control: "text" },
      ],
      defaultData: {
        title: "Terima Kasih",
        copy: "Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Anda berkenan hadir dan memberikan doa restu.",
        subtitle: "Ayu & Ardi",
        greeting: "Wassalamu’alaikum Warahmatullahi Wabarakatuh",
        date: "26 · 09 · 2026",
        imageLabel: "Foto penutup",
        imageUrl: photos.lampungCover,
      },
    },
  ],
  defaultSections: ["opening-envelope", "hero", "couple", "countdown", "event", "map", "unduh-mantu", "quote", "gallery", "gift", "wishes", "closing"],
});
