import { defineTemplate } from "../schema";

const theme = (
  id: string,
  label: string,
  colors: {
    background: string;
    surface: string;
    primary: string;
    accent: string;
    text: string;
    dark: string;
    rich: string;
    mid: string;
    cream: string;
    border: string;
    muted: string;
  }
) => ({
  id,
  label,
  colors,
  fonts: {
    display: "Plus Jakarta Sans",
    heading: "Plus Jakarta Sans",
    body: "Plus Jakarta Sans",
  },
});

export const aqiqahLittleBloom = defineTemplate({
  id: "aqiqah-little-bloom",
  code: "aqiqh",
  version: 1,
  category: "aqiqah",
  name: "Aqiqah Little Bloom",
  description: "Undangan tasyakuran walimatul aqiqah & kelahiran buah hati dengan nuansa pastel lembut, ornamen awan bintang emas, doa tasyakuran, dan galeri manis.",
  price: 1000,
  defaultMusicUrl: "/assets/audio/Playful-Sunshine.mp3",
  navigation: {
    scrollRootSelector: "[data-template-scroll-root]",
    sectionAttribute: "data-template-section",
    openingSectionId: "opening-envelope",
  },
  defaultView: "mobile",
  useContainer: true,
  themes: [
    theme("pastel-sky", "Sky Blue & Gold Moonlight", {
      background: "#f0f5fb",
      surface: "#ffffff",
      primary: "#2b537d",
      accent: "#d4af37",
      text: "#1e334a",
      dark: "#14283d",
      rich: "#3b6999",
      mid: "#608bb8",
      cream: "#f7fafc",
      border: "#cfe0f0",
      muted: "#6685a5",
    }),
    theme("blush-peach", "Blush Rose & Warm Gold", {
      background: "#fdf4f5",
      surface: "#ffffff",
      primary: "#8f4453",
      accent: "#d4af37",
      text: "#3d1f25",
      dark: "#2c1218",
      rich: "#b05d6e",
      mid: "#cf8694",
      cream: "#fff9fa",
      border: "#f3d1d7",
      muted: "#96656f",
    }),
    theme("sage-meadow", "Sage Green & Honey Gold", {
      background: "#f2f7f3",
      surface: "#ffffff",
      primary: "#355e42",
      accent: "#d9a74a",
      text: "#213628",
      dark: "#14241a",
      rich: "#4b7c5b",
      mid: "#76a384",
      cream: "#f8fbf8",
      border: "#d1e3d6",
      muted: "#66826e",
    }),
  ],
  sections: [
    {
      type: "opening-envelope",
      label: "Opening Envelope",
      description: "Amplop pastel mewah dengan pita dan segel starlight emas.",
      required: true,
      reorderable: false,
      maxInstances: 1,
      capabilities: { textStyle: true },
      fields: [
        { key: "kicker", label: "Teks Pembuka", control: "text" },
        { key: "title", label: "Nama Acara", control: "text" },
        { key: "subtitle", label: "Nama Buah Hati", control: "text" },
        { key: "date", label: "Tanggal Acara", control: "text" },
      ],
      defaultData: {
        title: "Tasyakuran Aqiqah",
        subtitle: "Muhammad Rayyan Al-Fatih",
        kicker: "UNDANGAN TASYAKURAN AQIQAH",
        date: "Ahad, 20 Desember 2026",
      },
    },
    {
      type: "hero",
      label: "Hero Header",
      description: "Ucapan bismillah, nama panggilan, countdown, dan foto baby.",
      required: true,
      reorderable: false,
      maxInstances: 1,
      capabilities: { textStyle: true, image: true, backgroundColor: true },
      fields: [
        { key: "bismillah", label: "Kalimat Bismillah", control: "text" },
        { key: "kicker", label: "Kicker / Badge", control: "text" },
        { key: "title", label: "Nama Lengkap Ananda", control: "text" },
        { key: "nickname", label: "Panggilan Sayang", control: "text" },
        { key: "date", label: "Tanggal Tasyakuran", control: "text" },
        { key: "eventDateIso", label: "Waktu Countdown (ISO/WIB)", control: "datetime-local" },
        { key: "copy", label: "Pesan Pembuka", control: "textarea", rows: 3 },
      ],
      defaultData: {
        title: "Muhammad Rayyan Al-Fatih",
        nickname: "Baby Rayyan",
        bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
        kicker: "✦ TASYAKURAN WALIMATUL AQIQAH ✦",
        date: "Ahad, 20 Desember 2026",
        eventDateIso: "2026-12-20T09:00:00+07:00",
        copy: "Puji dan syukur kami panjatkan ke hadirat Allah SWT atas karunia dan amanah kelahiran putra kami tercinta.",
        imageUrl: "/assets/aqiqah/baby-portrait.png",
        imageLabel: "Foto Baby Rayyan",
      },
    },
    {
      type: "prayer",
      label: "Ayat & Doa Aqiqah",
      description: "Kutipan hadits / ayat Al-Qur'an dan doa kebaikan anak.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: { textStyle: true, backgroundColor: true },
      fields: [
        { key: "arabic", label: "Teks Doa / Dalil (Arab)", control: "textarea", rows: 3 },
        { key: "translation", label: "Arti / Makna Terjemahan", control: "textarea", rows: 3 },
        { key: "source", label: "Sumber Hadits / Ayat", control: "text" },
      ],
      defaultData: {
        title: "Doa & Hadits Aqiqah",
        arabic: "كُلُّ غُلاَمٍ رَهِينَةٌ بِعَقِيقَتِهِ تُذْبَحُ عَنْهُ يَوْمَ سَابِعِهِ وَيُحْلَقُ وَيُسَمَّى",
        translation: "Setiap anak tergadaikan dengan aqiqahnya, disembelihkan untuknya pada hari ketujuh, dicukur rambutnya, dan diberi nama.",
        source: "— HR. Abu Dawud, At-Tirmidzi, & An-Nasa'i",
      },
    },
    {
      type: "profile",
      label: "Profil & Biodata Bayi",
      description: "Biodata kelahiran baby (jam, berat, panjang) dan nama orang tua.",
      required: true,
      reorderable: true,
      maxInstances: 1,
      capabilities: { textStyle: true, image: true, backgroundColor: true },
      fields: [
        { key: "eyebrow", label: "Teks Atas", control: "text" },
        { key: "childName", label: "Nama Lengkap Bayi", control: "text" },
        { key: "gender", label: "Keterangan Jenis Kelamin", control: "text" },
        { key: "birthDate", label: "Hari & Tanggal Lahir", control: "text" },
        { key: "birthTime", label: "Jam Lahir", control: "text" },
        { key: "birthWeight", label: "Berat Lahir", control: "text" },
        { key: "birthHeight", label: "Panjang Lahir", control: "text" },
        { key: "parents", label: "Nama Kedua Orang Tua", control: "text" },
        { key: "doa", label: "Untaian Doa Orang Tua", control: "textarea", rows: 4 },
      ],
      defaultData: {
        title: "Biodata Buah Hati",
        eyebrow: "PUTRA TERCINTA KAMI",
        childName: "Muhammad Rayyan Al-Fatih",
        gender: "Putra Pertama",
        birthDate: "Senin, 07 Desember 2026",
        birthTime: "Pukul 06.45 WIB",
        birthWeight: "3.35 kg",
        birthHeight: "50 cm",
        parents: "Putra dari Bpk. Irfan Maulana & Ibu Annisa Wardani",
        doa: "Semoga Allah SWT menjadikan ananda anak yang sholeh, cerdas, berakhlak mulia, berbakti kepada kedua orang tua, serta menjadi penyejuk hati bagi keluarga dan umat.",
        imageUrl: "/assets/aqiqah/baby-landscape.png",
        imageLabel: "Foto Baby Rayyan",
      },
    },
    {
      type: "event",
      label: "Rangkaian Acara",
      description: "Jadwal acara tasyakuran, lokasi, dan integrasi Google Maps.",
      required: true,
      reorderable: true,
      maxInstances: 1,
      capabilities: { textStyle: true, map: true, backgroundColor: true },
      fields: [
        { key: "eyebrow", label: "Teks Atas", control: "text" },
        { key: "title", label: "Judul Section", control: "text" },
        { key: "eventBadge", label: "Badge Acara", control: "text" },
        { key: "eventTitle", label: "Nama Acara", control: "text" },
        { key: "eventDate", label: "Hari & Tanggal Acara", control: "text" },
        { key: "eventTime", label: "Waktu Acara", control: "text" },
        { key: "venueName", label: "Nama Tempat / Kediaman", control: "text" },
        { key: "venueAddress", label: "Alamat Lengkap", control: "textarea", rows: 3 },
        { key: "mapUrl", label: "URL Google Maps", control: "url" },
        { key: "mapLabel", label: "Label Tombol Maps", control: "text" },
      ],
      defaultData: {
        title: "Rangkaian Acara Tasyakuran",
        eyebrow: "WAKTU & LOKASI",
        eventBadge: "Tasyakuran & Doa Bersama",
        eventTitle: "Walimatul Aqiqah & Potong Rambut",
        eventDate: "Ahad, 20 Desember 2026",
        eventTime: "Pukul 09.00 – 12.00 WIB",
        venueName: "Kediaman Keluarga Bpk. Irfan & Ibu Annisa",
        venueAddress: "Jl. Dahlia Indah No. 18, Kemang, Jakarta Selatan",
        mapUrl: "https://maps.google.com/?q=Jakarta",
        mapLabel: "Buka Google Maps",
      },
    },
    {
      type: "gallery",
      label: "Galeri Foto Baby",
      description: "Kumpulan foto menggemaskan momen awal buah hati.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: { gallery: true, backgroundColor: true },
      fields: [
        { key: "eyebrow", label: "Teks Atas", control: "text" },
        { key: "title", label: "Judul Galeri", control: "text" },
        { key: "description", label: "Deskripsi", control: "textarea", rows: 2 },
      ],
      defaultData: {
        title: "Galeri Buah Hati",
        eyebrow: "SWEET MOMENTS",
        description: "Potret kebahagiaan dan kehangatan menyambut kehadiran malaikat kecil kami.",
        imageUrls: [
          "/assets/aqiqah/baby-portrait.png",
          "/assets/aqiqah/baby-landscape.png"
        ],
        imageLabel: "Foto Galeri Rayyan",
      },
    },
    {
      type: "gift",
      label: "Amplop & Kado Digital",
      description: "Nomor rekening orang tua & alamat kirim kado untuk ananda.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: { textStyle: true, backgroundColor: true },
      fields: [
        { key: "eyebrow", label: "Teks Atas", control: "text" },
        { key: "title", label: "Judul Kado", control: "text" },
        { key: "description", label: "Pesan Pengantar", control: "textarea", rows: 3 },
        { key: "bank1Name", label: "Nama Bank / e-Wallet (1)", control: "text" },
        { key: "bank1Account", label: "Nomor Rekening (1)", control: "text" },
        { key: "bank1Holder", label: "Atas Nama (1)", control: "text" },
        { key: "bank2Name", label: "Nama Bank / e-Wallet (2)", control: "text" },
        { key: "bank2Account", label: "Nomor Rekening (2)", control: "text" },
        { key: "bank2Holder", label: "Atas Nama (2)", control: "text" },
        { key: "giftAddress", label: "Alamat Pengiriman Kado Fisik", control: "textarea", rows: 3 },
        { key: "giftRecipient", label: "Penerima Kado Fisik", control: "text" },
      ],
      defaultData: {
        title: "Tanda Kasih & Hadiah",
        eyebrow: "HADIAH DIGITAL",
        description: "Doa restu Anda merupakan karunia terindah bagi kami. Bagi keluarga dan sahabat yang ingin memberikan tanda kasih untuk ananda, dapat melalui transfer berikut:",
        bank1Name: "BCA",
        bank1Account: "8830192847",
        bank1Holder: "Irfan Maulana",
        bank2Name: "Bank Syariah Indonesia (BSI)",
        bank2Account: "7128394012",
        bank2Holder: "Annisa Wardani",
        giftRecipient: "Keluarga Rayyan (0812-3456-7890)",
        giftAddress: "Jl. Dahlia Indah No. 18, Kemang, Jakarta Selatan (12730)",
      },
    },
    {
      type: "wishes",
      label: "Buku Tamu & Ucapan",
      description: "Form kirim doa restu dan daftar ucapan para tamu.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: { textStyle: true, backgroundColor: true },
      fields: [
        { key: "eyebrow", label: "Teks Atas", control: "text" },
        { key: "title", label: "Judul Buku Tamu", control: "text" },
        { key: "description", label: "Deskripsi", control: "textarea", rows: 2 },
      ],
      defaultData: {
        title: "Untaian Doa & Ucapan",
        eyebrow: "GUESTBOOK",
        description: "Tinggalkan doa dan pesan hangat untuk ananda Muhammad Rayyan Al-Fatih.",
      },
    },
    {
      type: "closing",
      label: "Penutup & Ucapan Terima Kasih",
      description: "Pesan rasa syukur dan nama keluarga besar pengundang.",
      required: true,
      reorderable: true,
      maxInstances: 1,
      capabilities: { textStyle: true, backgroundColor: true },
      fields: [
        { key: "eyebrow", label: "Teks Atas", control: "text" },
        { key: "title", label: "Judul Penutup", control: "text" },
        { key: "message", label: "Pesan Penutup", control: "textarea", rows: 4 },
        { key: "family", label: "Keluarga Besar Pengundang", control: "text" },
      ],
      defaultData: {
        title: "Terima Kasih",
        eyebrow: "JAZAKUMULLAH KHAIRAN",
        message: "Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir serta memberikan doa restu bagi putra kami tercinta.",
        family: "Keluarga Besar Irfan Maulana & Annisa Wardani",
      },
    },
  ],
  defaultSections: [
    "opening-envelope",
    "hero",
    "prayer",
    "profile",
    "event",
    "gallery",
    "gift",
    "wishes",
    "closing",
  ],
});
