import type { TemplateKit } from "../contracts";

export const wisudaElegance: TemplateKit = {
  id: "wisuda-elegance",
  code: "wsdeg",
  version: 1,
  category: "wisuda",
  name: "Wisuda Elegance",
  description: "Undangan wisuda & syukuran kelulusan akademis bernuansa Academic Prestige yang megah, elegan, dan penuh rasa syukur.",
  price: 35000,
  defaultMusicUrl: "/assets/audio/Playful-Sunshine.mp3",
  defaultView: "mobile",
  useContainer: true,
  navigation: {
    scrollRootSelector: "[data-template-scroll-root]",
    sectionAttribute: "data-template-section",
    openingSectionId: "opening-envelope",
  },
  themes: [
    {
      id: "festive-celebration",
      label: "Festive Celebration (Colorful)",
      colors: {
        background: "#f8fafc",
        surface: "#ffffff",
        primary: "#1e1b4b",
        accent: "#6366f1",
        text: "#0f172a",
        dark: "#0f172a",
        rich: "#1e1b4b",
        mid: "#334155",
        cream: "#f1f5f9",
        border: "#e2e8f0",
        muted: "#64748b",
      },
      fonts: {
        display: "Outfit, sans-serif",
        heading: "Outfit, sans-serif",
        body: "Plus Jakarta Sans, sans-serif",
      },
    },
    {
      id: "vibrant-violet",
      label: "Joyful Violet & Coral",
      colors: {
        background: "#faf5ff",
        surface: "#ffffff",
        primary: "#3b0764",
        accent: "#ec4899",
        text: "#0f172a",
        dark: "#1e1b4b",
        rich: "#2e1065",
        mid: "#334155",
        cream: "#fdf4ff",
        border: "#e9d5ff",
        muted: "#64748b",
      },
      fonts: {
        display: "Outfit, sans-serif",
        heading: "Outfit, sans-serif",
        body: "Plus Jakarta Sans, sans-serif",
      },
    },
    {
      id: "ocean-cyan",
      label: "Bright Cyan & Royal Blue",
      colors: {
        background: "#f0f9ff",
        surface: "#ffffff",
        primary: "#0c4a6e",
        accent: "#06b6d4",
        text: "#0f172a",
        dark: "#082f49",
        rich: "#075985",
        mid: "#334155",
        cream: "#e0f2fe",
        border: "#bae6fd",
        muted: "#64748b",
      },
      fonts: {
        display: "Outfit, sans-serif",
        heading: "Outfit, sans-serif",
        body: "Plus Jakarta Sans, sans-serif",
      },
    },
    {
      id: "emerald-gold",
      label: "Academic Emerald & Gold Prestige",
      colors: {
        background: "#f0fdf4",
        surface: "#ffffff",
        primary: "#064e3b",
        accent: "#d97706",
        text: "#064e3b",
        dark: "#022c22",
        rich: "#047857",
        mid: "#1e293b",
        cream: "#ecfdf5",
        border: "#a7f3d0",
        muted: "#64748b",
      },
      fonts: {
        display: "Outfit, sans-serif",
        heading: "Outfit, sans-serif",
        body: "Plus Jakarta Sans, sans-serif",
      },
    },
  ],
  defaultSections: [
    "opening-envelope",
    "hero",
    "quote",
    "profile",
    "event",
    "gallery",
    "wishes",
    "closing",
  ],
  sections: [
    {
      type: "opening-envelope",
      label: "Opening Envelope",
      description: "Layar amplop pembuka dengan segel toga dan nama tamu.",
      required: true,
      reorderable: false,
      maxInstances: 1,
      capabilities: {
        textStyle: true,
        backgroundColor: false,
        backgroundImage: false,
        image: false,
        gallery: false,
        map: false,
      },
      fields: [
        { key: "title", label: "Judul Undangan", control: "text" },
        { key: "graduateName", label: "Nama & Gelar Wisudawan", control: "text" },
        { key: "university", label: "Nama Universitas", control: "text" },
        { key: "subtitle", label: "Salam Pembuka Tamu", control: "text" },
        { key: "buttonLabel", label: "Teks Tombol Buka", control: "text" },
      ],
      defaultData: {
        title: "Undangan Wisuda",
        graduateName: "Anindya Putri Rahayu, S.Kom",
        university: "Universitas Indonesia",
        subtitle: "Spesial mengundang Bapak/Ibu/Sahabat:",
        buttonLabel: "Buka Undangan",
      },
    },
    {
      type: "hero",
      label: "Hero Wisudawan",
      description: "Header utama foto toga, nama & gelar, fakultas, dan countdown wisuda.",
      required: true,
      reorderable: false,
      maxInstances: 1,
      capabilities: {
        textStyle: true,
        backgroundColor: true,
        backgroundImage: true,
        image: true,
        gallery: false,
        map: false,
      },
      fields: [
        { key: "kicker", label: "Kicker / Badge", control: "text" },
        { key: "title", label: "Judul Header", control: "text" },
        { key: "graduateName", label: "Nama Wisudawan", control: "text" },
        { key: "degree", label: "Gelar Akademik", control: "text" },
        { key: "university", label: "Nama Universitas", control: "text" },
        { key: "faculty", label: "Fakultas & Program Studi", control: "text" },
        { key: "date", label: "Tanggal Wisuda", control: "text" },
        { key: "eventDateCountdown", label: "Tanggal Countdown (ISO / YYYY-MM-DD)", control: "text" },
        { key: "photoUrl", label: "Foto Utama Wisudawan", control: "text" },
        { key: "scrollHint", label: "Petunjuk Scroll", control: "text" },
      ],
      defaultData: {
        kicker: "🎉 Momen Kelulusan & Selebrasi 🎉",
        title: "Perayaan Kelulusan & Wisuda",
        graduateName: "Anindya Putri Rahayu",
        degree: "S.Kom",
        university: "Universitas Indonesia",
        faculty: "Fakultas Ilmu Komputer · Sistem Informasi",
        date: "Sabtu, 17 Oktober 2026",
        eventDateCountdown: "2026-10-17T08:00:00",
        photoUrl: "",
        scrollHint: "Gulir ke bawah untuk info selengkapnya",
      },
    },
    {
      type: "quote",
      label: "Ucapan Syukur & Kutipan",
      description: "Pesan terima kasih kepada orang tua, dosen, dan ungkapan rasa syukur.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: {
        textStyle: true,
        backgroundColor: true,
        backgroundImage: true,
        image: true,
        gallery: false,
        map: false,
      },
      fields: [
        { key: "title", label: "Judul Kutipan", control: "text" },
        { key: "quoteText", label: "Teks Pesan / Kutipan", control: "textarea" },
        { key: "author", label: "Nama Penulis / Wisudawan", control: "text" },
        { key: "photoUrl", label: "Foto / Ilustrasi", control: "text" },
      ],
      defaultData: {
        title: "Ungkapan Syukur & Apresiasi",
        quoteText: "Tiada capaian terindah tanpa doa tulus orang tua, bimbingan para dosen tercinta, dan kebersamaan keluarga serta sahabat. Hari kelulusan ini adalah awal dari langkah baru menuju masa depan yang penuh berkah.",
        author: "Anindya Putri Rahayu, S.Kom",
        photoUrl: "",
      },
    },
    {
      type: "profile",
      label: "Profil Akademik",
      description: "Biodata wisudawan, nama kampus, fakultas, jurusan, dan gelar kelulusan.",
      required: true,
      reorderable: true,
      maxInstances: 1,
      capabilities: {
        textStyle: true,
        backgroundColor: true,
        backgroundImage: true,
        image: true,
        gallery: false,
        map: false,
      },
      fields: [
        { key: "title", label: "Judul Section", control: "text" },
        { key: "graduateName", label: "Nama Lengkap & Gelar", control: "text" },
        { key: "degree", label: "Jenjang & Gelar", control: "text" },
        { key: "university", label: "Nama Universitas / Kampus", control: "text" },
        { key: "faculty", label: "Fakultas", control: "text" },
        { key: "major", label: "Program Studi / Jurusan", control: "text" },
        { key: "period", label: "Periode Wisuda / Kelulusan", control: "text" },
        { key: "photoUrl", label: "Foto Profil / Medali (Opsional)", control: "text" },
      ],
      defaultData: {
        title: "Profil Wisudawan",
        graduateName: "Anindya Putri Rahayu, S.Kom",
        degree: "Sarjana Komputer (S.Kom)",
        university: "Universitas Indonesia",
        faculty: "Fakultas Ilmu Komputer",
        major: "Program Studi Sistem Informasi",
        period: "Wisuda Program Sarjana Periode Genap 2025/2026",
        photoUrl: "",
      },
    },
    {
      type: "event",
      label: "Rangkaian Acara",
      description: "Waktu dan lokasi prosesi wisuda serta jamuan santap bersama.",
      required: true,
      reorderable: true,
      maxInstances: 1,
      capabilities: {
        textStyle: true,
        backgroundColor: true,
        backgroundImage: true,
        image: false,
        gallery: false,
        map: true,
      },
      fields: [
        { key: "title", label: "Judul Section", control: "text" },
        { key: "subtitle", label: "Sub Judul", control: "text" },
        { key: "ceremonyName", label: "Nama Acara (Prosesi Wisuda)", control: "text" },
        { key: "ceremonyTime", label: "Waktu Acara", control: "text" },
        { key: "ceremonyVenue", label: "Tempat Acara", control: "text" },
        { key: "ceremonyMapUrl", label: "URL Google Maps", control: "url" },
        { key: "ceremonyMapLabel", label: "Label Tombol Peta", control: "text" },
        { key: "calendarUrl", label: "URL Google Calendar", control: "url" },
        { key: "calendarLabel", label: "Label Tombol Kalender", control: "text" },
      ],
      defaultData: {
        title: "Rangkaian Acara",
        subtitle: "Jadwal prosesi upacara kelulusan wisuda",
        ceremonyName: "Upacara Wisuda",
        ceremonyTime: "Pukul 08.00 - 11.30 WIB",
        ceremonyVenue: "Balairung Utama Universitas Indonesia, Depok",
        ceremonyMapUrl: "https://maps.app.goo.gl/wKxJ8Lh8D3H5N9Vq8",
        ceremonyMapLabel: "Buka Google Maps",
        calendarUrl: "https://calendar.google.com/calendar/render?action=TEMPLATE&text=Upacara+Wisuda+Anindya+Putri+Rahayu&dates=20261017T010000Z/20261017T043000Z&details=Upacara+Wisuda+dan+Kelulusan+Anindya+Putri+Rahayu%2C+S.Kom&location=Balairung+Utama+Universitas+Indonesia%2C+Depok",
        calendarLabel: "Simpan ke Kalender",
      },
    },
    {
      type: "gallery",
      label: "Galeri Kenangan",
      description: "Frame foto momen perjuangan kuliah dan studio wisuda.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: {
        textStyle: true,
        backgroundColor: true,
        backgroundImage: true,
        image: false,
        gallery: true,
        map: false,
      },
      fields: [
        { key: "title", label: "Judul Galeri", control: "text" },
        { key: "subtitle", label: "Deskripsi Singkat", control: "text" },
      ],
      defaultData: {
        title: "Momen & Kenangan",
        subtitle: "Rekam jejak perjalanan studi, dedikasi akademis, dan selebrasi bersama keluarga serta sahabat tercinta",
        imageUrls: [],
        imageLabel: "Pilih foto kenangan dari Asset Manager",
      },
    },
    {
      type: "wishes",
      label: "Kirim Ucapan",
      description: "Ucapan selamat kelulusan dan doa dari tamu undangan.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: {
        textStyle: true,
        backgroundColor: true,
        backgroundImage: true,
        image: false,
        gallery: false,
        map: false,
      },
      fields: [
        { key: "title", label: "Judul Ucapan", control: "text" },
        { key: "subtitle", label: "Sub Judul", control: "text" },
      ],
      defaultData: {
        title: "Kirim Ucapan & Doa",
        subtitle: "Tinggalkan ucapan selamat dan doa terbaik untuk kelulusan wisudawati",
      },
    },
    {
      type: "closing",
      label: "Doa & Penutup",
      description: "Ucapan terima kasih dari wisudawan beserta keluarga besar.",
      required: true,
      reorderable: false,
      maxInstances: 1,
      capabilities: {
        textStyle: true,
        backgroundColor: true,
        backgroundImage: true,
        image: true,
        gallery: false,
        map: false,
      },
      fields: [
        { key: "title", label: "Judul Penutup", control: "text" },
        { key: "message", label: "Pesan Penutup", control: "textarea" },
        { key: "familySignature", label: "Tanda Tangan / Nama Keluarga", control: "text" },
        { key: "photoUrl", label: "Foto Latar / Aksen Penutup", control: "text" },
      ],
      defaultData: {
        title: "Terima Kasih",
        message: "Merupakan suatu kehormatan dan kebahagiaan bagi kami sekeluarga atas kehadiran, dukungan, dan ucapan tulus dari Bapak/Ibu/Saudara/i sekalian.",
        familySignature: "Anindya Putri Rahayu, S.Kom & Keluarga Besar",
        photoUrl: "",
      },
    },
  ],
};
