import { defineTemplate } from "../schema";

const theme = (
  id: string,
  label: string,
  colors: {
    background: string;
    surface: string;
    primary: string;
    accent: string;
    text: string;
    dark: string;
    rich: string;
    mid: string;
    cream: string;
    border: string;
    muted: string;
  }
) => ({
  id,
  label,
  colors,
  fonts: {
    display: "Cinzel",
    heading: "Cormorant Garamond",
    body: "Plus Jakarta Sans",
  },
});

export const khitanKsatriaJawa = defineTemplate({
  id: "khitan-ksatria-jawa",
  code: "khtnn",
  version: 1,
  category: "khitanan",
  name: "Ksatria Khitan Jawa",
  description: "Undangan syukuran walimatul khitan bernuansa Keraton Jawa & Islami yang agung, gagah, dan berakhlak mulia.",
  price: 35000,
  navigation: {
    scrollRootSelector: "[data-template-scroll-root]",
    sectionAttribute: "data-template-section",
    openingSectionId: "opening-envelope",
  },
  defaultView: "mobile",
  useContainer: true,
  themes: [
    theme("keraton-emerald", "Keraton Emerald & Gold", {
      background: "#faf7f0",
      surface: "#ffffff",
      primary: "#1b382b",
      accent: "#d4af37",
      text: "#202d24",
      dark: "#0e1f17",
      rich: "#2d4a3b",
      mid: "#517460",
      cream: "#f7f1e1",
      border: "#dcd1ba",
      muted: "#6b7c71",
    }),
    theme("midnight-navy", "Midnight Navy & Gold", {
      background: "#f4f6fa",
      surface: "#ffffff",
      primary: "#16213e",
      accent: "#e5b95c",
      text: "#1e293b",
      dark: "#0f172a",
      rich: "#1e2d4d",
      mid: "#3b4f73",
      cream: "#f8f5eb",
      border: "#cbd5e1",
      muted: "#64748b",
    }),
    theme("sogan-terracotta", "Batik Sogan & Warm Terracotta", {
      background: "#fbf8f3",
      surface: "#ffffff",
      primary: "#5c3d2e",
      accent: "#d99b38",
      text: "#362217",
      dark: "#2b1810",
      rich: "#48281b",
      mid: "#805943",
      cream: "#f5ecdb",
      border: "#dfd2c0",
      muted: "#7c685b",
    }),
  ],
  sections: [
    {
      type: "opening-envelope",
      label: "Opening Envelope",
      description: "Amplop batik keraton dengan segel gunungan wayang emas.",
      required: true,
      reorderable: false,
      maxInstances: 1,
      capabilities: { textStyle: true },
      fields: [
        { key: "kicker", label: "Teks Pembuka", control: "text" },
        { key: "title", label: "Nama Acara", control: "text" },
        { key: "subtitle", label: "Nama Ananda", control: "text" },
        { key: "date", label: "Tanggal Acara", control: "text" },
      ],
      defaultData: {
        kicker: "UNDANGAN WALIMATUL KHITAN",
        title: "Walimatul Khitan",
        subtitle: "Raden Mas Arya Pratama",
        date: "Ahad, 15 November 2026",
      },
    },
    {
      type: "hero",
      label: "Hero Ksatria",
      description: "Header utama foto ksatria dan doa pembuka.",
      required: true,
      reorderable: false,
      maxInstances: 1,
      capabilities: { image: true, backgroundImage: true, backgroundColor: true, textStyle: true },
      fields: [
        { key: "bismillah", label: "Kaligrafi Basmalah", control: "text" },
        { key: "kicker", label: "Label Acara", control: "text" },
        { key: "title", label: "Nama Ananda", control: "text" },
        { key: "date", label: "Tanggal & Hari", control: "text" },
        { key: "copy", label: "Pesan Pembuka", control: "textarea", rows: 2 },
      ],
      defaultData: {
        bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
        kicker: "✦ WALIMATUL KHITAN ✦",
        title: "Raden Mas Arya Pratama",
        date: "Ahad, 15 November 2026",
        copy: "Menunaikan Sunnah Rasulullah SAW demi Menjadi Generasi Shalih, Berbakti, dan Budi Pekerti Mulia.",
        imageUrl: "/assets/khitanan/1.jpeg",
        imageLabel: "Pilih foto utama Ananda dari Asset Manager",
      },
    },
    {
      type: "profile",
      label: "Profil Ananda",
      description: "Biodata Ananda Khitan dan untaian doa orang tua.",
      required: true,
      reorderable: true,
      maxInstances: 1,
      capabilities: { image: true, backgroundColor: true, textStyle: true },
      fields: [
        { key: "eyebrow", label: "Label Section", control: "text" },
        { key: "title", label: "Judul Section", control: "text" },
        { key: "childName", label: "Nama Lengkap Ananda", control: "text" },
        { key: "nickname", label: "Nama Panggilan", control: "text" },
        { key: "parents", label: "Nama Orang Tua", control: "text" },
        { key: "familyNote", label: "Keterangan Bersama Orang Tua", control: "textarea", rows: 2 },
        { key: "doa", label: "Untaian Doa", control: "textarea", rows: 3 },
      ],
      defaultData: {
        eyebrow: "SANG KSATRIA KELUARGA",
        title: "Profil Ananda Tercinta",
        childName: "Raden Mas Arya Pratama",
        nickname: "Ananda Arya",
        parents: "Putra Pertama dari Bpk. Bambang Wijaya & Ibu Siti Rahayu",
        familyNote: "Mendampingi ananda tercinta dalam balutan busana adat ageng Keraton Jawa penuh doa dan restu.",
        doa: "Semoga Allah SWT senantiasa melimpahkan taufik, hidayah, dan kesehatan, menjadikannya anak yang sholeh, berbakti kepada kedua orang tua, cerdas berakhlak, serta berguna bagi nusa, bangsa, dan agama.",
        imageUrl: "/assets/khitanan/7.jpeg",
        imageLabel: "Pilih foto profil / bersama orang tua dari Asset Manager",
      },
    },
    {
      type: "event",
      label: "Detail Acara",
      description: "Waktu, lokasi, dan panduan Google Maps.",
      required: true,
      reorderable: true,
      maxInstances: 1,
      capabilities: { backgroundColor: true, map: true, textStyle: true },
      fields: [
        { key: "eyebrow", label: "Label Section", control: "text" },
        { key: "title", label: "Judul Section", control: "text" },
        { key: "eventBadge", label: "Label Sesi Acara", control: "text" },
        { key: "eventTitle", label: "Nama Acara", control: "text" },
        { key: "eventTime", label: "Waktu Acara", control: "text" },
        { key: "locationName", label: "Nama Tempat/Gedung", control: "text" },
        { key: "address", label: "Alamat Lengkap", control: "textarea", rows: 2 },
        { key: "mapUrl", label: "URL Google Maps", control: "url" },
        { key: "mapLabel", label: "Teks Tombol Peta", control: "text" },
        { key: "calendarUrl", label: "URL Google Calendar", control: "url" },
        { key: "calendarLabel", label: "Teks Tombol Kalender", control: "text" },
      ],
      defaultData: {
        eyebrow: "WAKTU & LOKASI SYUKURAN",
        title: "Rangkaian Acara Khitanan",
        eventBadge: "Syukuran Khitan",
        eventTitle: "Doa Syukuran Khitan",
        eventTime: "Pukul 08.30 – 11.30 WIB",
        locationName: "Gedung Sasana Kriya Keraton",
        address: "Jl. Pangeran Antasari No. 88, Kedamaian, Kota Bandar Lampung",
        mapUrl: "https://maps.google.com/?q=Bandar+Lampung",
        mapLabel: "Buka Google Maps",
        calendarUrl: "https://calendar.google.com/calendar/render?action=TEMPLATE&text=Walimatul%20Khitan%20Raden%20Mas%20Arya%20Pratama&dates=20261115T013000Z/20261115T043000Z&details=Doa%20Syukuran%20Khitan%20Raden%20Mas%20Arya%20Pratama&location=Gedung%20Sasana%20Kriya%20Keraton%2C%20Jl.%20Pangeran%20Antasari%20No.%2088%2C%20Kedamaian%2C%20Bandar%20Lampung",
        calendarLabel: "Simpan ke Kalender",
      },
    },
    {
      type: "gallery",
      label: "Galeri Foto",
      description: "Album kenangan dan potret gagah Sang Ksatria.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: { gallery: true, backgroundColor: true, textStyle: true },
      fields: [
        { key: "eyebrow", label: "Label Section", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "subtitle", label: "Caption / Keterangan", control: "text" },
      ],
      defaultData: {
        eyebrow: "ALBUM KENANGAN",
        title: "Galeri Sang Ksatria",
        subtitle: "Senyum, wibawa, dan langkah awal kedewasaan Ananda Arya.",
        imageLabel: "Pilih foto galeri",
        imageUrls: [
          "/assets/khitanan/1.jpeg",
          "/assets/khitanan/2.jpeg",
          "/assets/khitanan/3.jpeg",
          "/assets/khitanan/4.jpeg",
          "/assets/khitanan/5.jpeg",
          "/assets/khitanan/6.jpeg",
          "/assets/khitanan/7.jpeg",
        ],
      },
    },
    {
      type: "gift",
      label: "Tanda Kasih / Hadiah",
      description: "Rekening transfer dan QRIS hadiah digital.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: { image: true, backgroundColor: true, textStyle: true },
      fields: [
        { key: "eyebrow", label: "Label Section", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "subtitle", label: "Deskripsi", control: "textarea", rows: 2 },
        { key: "bank", label: "Nama Bank 1", control: "text" },
        { key: "account", label: "Nomor Rekening 1", control: "text" },
        { key: "holder", label: "Atas Nama Rekening 1", control: "text" },
        { key: "bank2", label: "Nama Bank 2", control: "text" },
        { key: "account2", label: "Nomor Rekening 2", control: "text" },
        { key: "holder2", label: "Atas Nama Rekening 2", control: "text" },
        { key: "qrisLabel", label: "Label QRIS", control: "text" },
      ],
      defaultData: {
        eyebrow: "TANDA KASIH & DOA",
        title: "Kirim Hadiah Digital",
        subtitle: "Kehadiran dan doa restu Bapak/Ibu/Saudara/i merupakan kebahagiaan tak terhingga bagi kami. Apabila berkenan memberikan tanda kasih bagi Ananda Arya, dapat melalui:",
        bank: "BANK BCA",
        account: "7820 1829 90",
        holder: "a.n. Bambang Wijaya (Ayah)",
        bank2: "BANK MANDIRI",
        account2: "1140 0293 8472 1",
        holder2: "a.n. Siti Rahayu (Ibu)",
        qrisLabel: "Scan QRIS Tanda Kasih",
        imageUrl: "",
        imageLabel: "Pilih gambar barcode QRIS dari Asset Manager",
      },
    },
    {
      type: "wishes",
      label: "Buku Tamu & Doa Restu",
      description: "Untaian doa restu dari para tamu undangan.",
      required: false,
      reorderable: true,
      maxInstances: 1,
      capabilities: { backgroundColor: true, textStyle: true },
      fields: [
        { key: "eyebrow", label: "Label Section", control: "text" },
        { key: "title", label: "Judul", control: "text" },
        { key: "subtitle", label: "Deskripsi", control: "textarea", rows: 2 },
      ],
      defaultData: {
        eyebrow: "UNTAIAN DOA RESTU",
        title: "Buku Tamu & Ucapan",
        subtitle: "Tuliskan doa serta pesan hangat Anda untuk mengiringi langkah Ananda Arya.",
      },
    },
    {
      type: "closing",
      label: "Doa Penutup & Terima Kasih",
      description: "Ungkapan terima kasih dan hamdalah keluarga.",
      required: true,
      reorderable: false,
      maxInstances: 1,
      capabilities: { backgroundColor: true, textStyle: true },
      fields: [
        { key: "eyebrow", label: "Label Penutup", control: "text" },
        { key: "title", label: "Judul Penutup", control: "text" },
        { key: "subtitle", label: "Pesan Terima Kasih", control: "textarea", rows: 2 },
        { key: "family", label: "Keluarga Besar", control: "text" },
      ],
      defaultData: {
        eyebrow: "JAZAKUMULLAH KHAIRAN KATSIRAN",
        title: "Matur Nuwun",
        subtitle: "Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir serta memberikan doa restu bagi Ananda tercinta.",
        family: "Keluarga Besar Bpk. Bambang Wijaya & Ibu Siti Rahayu",
      },
    },
  ],
  defaultSections: [
    "opening-envelope",
    "hero",
    "profile",
    "event",
    "gallery",
    "gift",
    "wishes",
    "closing",
  ],
});
